In [1]:
import numpy as np

### Rank 1 array issue
Do not use rank 1 arrays, but instead compute a column vector / matrix or a row vector.

In [2]:
# Create 5 random gaussian variables in array a
a = np.random.randn(5)

In [3]:
print(a)

[-0.93785766 -0.31467646 -0.22475363  0.70553048  0.55830967]


In [4]:
print(a.shape) # Rank 1 array, not 1-by-5 array!. Leads to non-intuitive results

(5,)


In [5]:
print(a.T) # a Transpose returns same array

[-0.93785766 -0.31467646 -0.22475363  0.70553048  0.55830967]


In [6]:
print(np.dot(a,a.T))

1.8385954059052163


In [8]:
a = np.random.randn(5,1)  # 1 by 5 matrix
print(a)

[[ 0.03611413]
 [-1.39583869]
 [-0.24704314]
 [-0.70811227]
 [ 1.56996767]]


In [9]:
print(a.T)  # a Transpose is a row vector now

[[ 0.03611413 -1.39583869 -0.24704314 -0.70811227  1.56996767]]


In [10]:
print(np.dot(a,a.T)) # Product between a and a Transpose -> gives outer product of the vector

[[ 1.30423074e-03 -5.04095069e-02 -8.92174918e-03 -2.55728620e-02
   5.66980244e-02]
 [-5.04095069e-02  1.94836565e+00  3.44832369e-01  9.88410501e-01
  -2.19142162e+00]
 [-8.92174918e-03  3.44832369e-01  6.10303114e-02  1.74934276e-01
  -3.87849738e-01]
 [-2.55728620e-02  9.88410501e-01  1.74934276e-01  5.01422983e-01
  -1.11171337e+00]
 [ 5.66980244e-02 -2.19142162e+00 -3.87849738e-01 -1.11171337e+00
   2.46479849e+00]]


In [13]:
assert(a.shape == (5,1))   # Use assertion statements to check whether data fits desired format.

In [14]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

In [15]:
c.shape

(12288, 45)

In [16]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c)

[[ 0.48163983 -0.1593506   1.73473511]
 [-0.0518873  -0.12839794  0.06386926]
 [-1.30368884  0.7107199   2.65749643]]


In [17]:
c.shape

(3, 3)